// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/media_metadata/mediametadata_service.proto

package mediametadata_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateNewMediaMetadataRequest struct {
	Name                     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SiteName                 string   `protobuf:"bytes,2,opt,name=siteName,proto3" json:"siteName,omitempty"`
	Length                   int32    `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Status                   int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Thumbnail                string   `protobuf:"bytes,5,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	ProjectId                int32    `protobuf:"varint,6,opt,name=projectId,proto3" json:"projectId,omitempty"`
	AwsBucketWholeMedia      string   `protobuf:"bytes,7,opt,name=awsBucketWholeMedia,proto3" json:"awsBucketWholeMedia,omitempty"`
	AwsStorageNameWholeMedia string   `protobuf:"bytes,8,opt,name=awsStorageNameWholeMedia,proto3" json:"awsStorageNameWholeMedia,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *CreateNewMediaMetadataRequest) Reset()         { *m = CreateNewMediaMetadataRequest{} }
func (m *CreateNewMediaMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNewMediaMetadataRequest) ProtoMessage()    {}
func (*CreateNewMediaMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a2cef8a9a3cc635, []int{0}
}

func (m *CreateNewMediaMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewMediaMetadataRequest.Unmarshal(m, b)
}
func (m *CreateNewMediaMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewMediaMetadataRequest.Marshal(b, m, deterministic)
}
func (m *CreateNewMediaMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewMediaMetadataRequest.Merge(m, src)
}
func (m *CreateNewMediaMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNewMediaMetadataRequest.Size(m)
}
func (m *CreateNewMediaMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewMediaMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewMediaMetadataRequest proto.InternalMessageInfo

func (m *CreateNewMediaMetadataRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateNewMediaMetadataRequest) GetSiteName() string {
	if m != nil {
		return m.SiteName
	}
	return ""
}

func (m *CreateNewMediaMetadataRequest) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *CreateNewMediaMetadataRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateNewMediaMetadataRequest) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *CreateNewMediaMetadataRequest) GetProjectId() int32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *CreateNewMediaMetadataRequest) GetAwsBucketWholeMedia() string {
	if m != nil {
		return m.AwsBucketWholeMedia
	}
	return ""
}

func (m *CreateNewMediaMetadataRequest) GetAwsStorageNameWholeMedia() string {
	if m != nil {
		return m.AwsStorageNameWholeMedia
	}
	return ""
}

type MediaMetadataResponse struct {
	MediaId                  int32    `protobuf:"varint,1,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	Name                     string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SiteName                 string   `protobuf:"bytes,3,opt,name=siteName,proto3" json:"siteName,omitempty"`
	Length                   int32    `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Status                   int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Thumbnail                string   `protobuf:"bytes,6,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	ProjectId                int32    `protobuf:"varint,7,opt,name=projectId,proto3" json:"projectId,omitempty"`
	AwsBucketWholeMedia      string   `protobuf:"bytes,8,opt,name=awsBucketWholeMedia,proto3" json:"awsBucketWholeMedia,omitempty"`
	AwsStorageNameWholeMedia string   `protobuf:"bytes,9,opt,name=awsStorageNameWholeMedia,proto3" json:"awsStorageNameWholeMedia,omitempty"`
	Keywords                 []string `protobuf:"bytes,10,rep,name=keywords,proto3" json:"keywords,omitempty"`
	CreatedAt                int64    `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt                int64    `protobuf:"varint,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *MediaMetadataResponse) Reset()         { *m = MediaMetadataResponse{} }
func (m *MediaMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*MediaMetadataResponse) ProtoMessage()    {}
func (*MediaMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a2cef8a9a3cc635, []int{1}
}

func (m *MediaMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaMetadataResponse.Unmarshal(m, b)
}
func (m *MediaMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaMetadataResponse.Marshal(b, m, deterministic)
}
func (m *MediaMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaMetadataResponse.Merge(m, src)
}
func (m *MediaMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_MediaMetadataResponse.Size(m)
}
func (m *MediaMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MediaMetadataResponse proto.InternalMessageInfo

func (m *MediaMetadataResponse) GetMediaId() int32 {
	if m != nil {
		return m.MediaId
	}
	return 0
}

func (m *MediaMetadataResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MediaMetadataResponse) GetSiteName() string {
	if m != nil {
		return m.SiteName
	}
	return ""
}

func (m *MediaMetadataResponse) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *MediaMetadataResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MediaMetadataResponse) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *MediaMetadataResponse) GetProjectId() int32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *MediaMetadataResponse) GetAwsBucketWholeMedia() string {
	if m != nil {
		return m.AwsBucketWholeMedia
	}
	return ""
}

func (m *MediaMetadataResponse) GetAwsStorageNameWholeMedia() string {
	if m != nil {
		return m.AwsStorageNameWholeMedia
	}
	return ""
}

func (m *MediaMetadataResponse) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *MediaMetadataResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *MediaMetadataResponse) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type UpdateMediaRequest struct {
	MediaId                  int32    `protobuf:"varint,1,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	Name                     string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SiteName                 string   `protobuf:"bytes,3,opt,name=siteName,proto3" json:"siteName,omitempty"`
	Length                   int32    `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Status                   int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Thumbnail                string   `protobuf:"bytes,6,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	ProjectId                int32    `protobuf:"varint,7,opt,name=projectId,proto3" json:"projectId,omitempty"`
	AwsBucketWholeMedia      string   `protobuf:"bytes,8,opt,name=awsBucketWholeMedia,proto3" json:"awsBucketWholeMedia,omitempty"`
	AwsStorageNameWholeMedia string   `protobuf:"bytes,9,opt,name=awsStorageNameWholeMedia,proto3" json:"awsStorageNameWholeMedia,omitempty"`
	CreatedAt                int64    `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *UpdateMediaRequest) Reset()         { *m = UpdateMediaRequest{} }
func (m *UpdateMediaRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMediaRequest) ProtoMessage()    {}
func (*UpdateMediaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a2cef8a9a3cc635, []int{2}
}

func (m *UpdateMediaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMediaRequest.Unmarshal(m, b)
}
func (m *UpdateMediaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMediaRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMediaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMediaRequest.Merge(m, src)
}
func (m *UpdateMediaRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMediaRequest.Size(m)
}
func (m *UpdateMediaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMediaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMediaRequest proto.InternalMessageInfo

func (m *UpdateMediaRequest) GetMediaId() int32 {
	if m != nil {
		return m.MediaId
	}
	return 0
}

func (m *UpdateMediaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateMediaRequest) GetSiteName() string {
	if m != nil {
		return m.SiteName
	}
	return ""
}

func (m *UpdateMediaRequest) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *UpdateMediaRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateMediaRequest) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *UpdateMediaRequest) GetProjectId() int32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *UpdateMediaRequest) GetAwsBucketWholeMedia() string {
	if m != nil {
		return m.AwsBucketWholeMedia
	}
	return ""
}

func (m *UpdateMediaRequest) GetAwsStorageNameWholeMedia() string {
	if m != nil {
		return m.AwsStorageNameWholeMedia
	}
	return ""
}

func (m *UpdateMediaRequest) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type GetMediaMetadataRequest struct {
	MediaId              int32    `protobuf:"varint,1,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMediaMetadataRequest) Reset()         { *m = GetMediaMetadataRequest{} }
func (m *GetMediaMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*GetMediaMetadataRequest) ProtoMessage()    {}
func (*GetMediaMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a2cef8a9a3cc635, []int{3}
}

func (m *GetMediaMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMediaMetadataRequest.Unmarshal(m, b)
}
func (m *GetMediaMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMediaMetadataRequest.Marshal(b, m, deterministic)
}
func (m *GetMediaMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMediaMetadataRequest.Merge(m, src)
}
func (m *GetMediaMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_GetMediaMetadataRequest.Size(m)
}
func (m *GetMediaMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMediaMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMediaMetadataRequest proto.InternalMessageInfo

func (m *GetMediaMetadataRequest) GetMediaId() int32 {
	if m != nil {
		return m.MediaId
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateNewMediaMetadataRequest)(nil), "CreateNewMediaMetadataRequest")
	proto.RegisterType((*MediaMetadataResponse)(nil), "MediaMetadataResponse")
	proto.RegisterType((*UpdateMediaRequest)(nil), "UpdateMediaRequest")
	proto.RegisterType((*GetMediaMetadataRequest)(nil), "GetMediaMetadataRequest")
}

func init() {
	proto.RegisterFile("proto/media_metadata/mediametadata_service.proto", fileDescriptor_1a2cef8a9a3cc635)
}

var fileDescriptor_1a2cef8a9a3cc635 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x94, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xc7, 0xc9, 0x67, 0xdb, 0x01, 0xa4, 0x95, 0x2b, 0x16, 0x6b, 0x05, 0x28, 0xca, 0xa9, 0xa7,
	0xb0, 0x62, 0x6f, 0xdc, 0x58, 0x10, 0x68, 0x25, 0xda, 0x43, 0x10, 0xe2, 0x58, 0xb9, 0xc9, 0x28,
	0x0d, 0x6d, 0x3e, 0x88, 0x1d, 0x22, 0x9e, 0x83, 0xa7, 0xe0, 0x85, 0x78, 0x09, 0x5e, 0x02, 0xd9,
	0x69, 0x12, 0x28, 0x75, 0x40, 0x9c, 0xf7, 0xd6, 0xff, 0x7f, 0x3c, 0x53, 0xcf, 0xcf, 0x93, 0x81,
	0xcb, 0xb2, 0x2a, 0x44, 0xf1, 0x34, 0xc3, 0x38, 0x65, 0xeb, 0x0c, 0x05, 0x8b, 0x99, 0x60, 0xad,
	0xec, 0xd4, 0x9a, 0x63, 0xf5, 0x39, 0x8d, 0x30, 0x50, 0x47, 0xfd, 0x6f, 0x26, 0x3c, 0x7e, 0x59,
	0x21, 0x13, 0xb8, 0xc2, 0x66, 0x29, 0x0f, 0x2e, 0x0f, 0x07, 0x43, 0xfc, 0x54, 0x23, 0x17, 0x84,
	0x80, 0x9d, 0xb3, 0x0c, 0xa9, 0xe1, 0x19, 0x8b, 0x59, 0xa8, 0x7e, 0x93, 0x0b, 0x98, 0xf2, 0x54,
	0xe0, 0x4a, 0xfa, 0xa6, 0xf2, 0x7b, 0x4d, 0xce, 0xc1, 0xdd, 0x63, 0x9e, 0x88, 0x2d, 0xb5, 0x3c,
	0x63, 0xe1, 0x84, 0x07, 0x25, 0x7d, 0x2e, 0x98, 0xa8, 0x39, 0xb5, 0x5b, 0xbf, 0x55, 0xe4, 0x11,
	0xcc, 0xc4, 0xb6, 0xce, 0x36, 0x39, 0x4b, 0xf7, 0xd4, 0x51, 0xc5, 0x06, 0x43, 0x46, 0xcb, 0xaa,
	0xf8, 0x88, 0x91, 0xb8, 0x89, 0xa9, 0xab, 0x12, 0x07, 0x83, 0x5c, 0xc2, 0x9c, 0x35, 0xfc, 0xba,
	0x8e, 0x76, 0x28, 0x3e, 0x6c, 0x8b, 0x3d, 0xaa, 0x0e, 0xe8, 0x44, 0x55, 0x39, 0x15, 0x22, 0xcf,
	0x81, 0xb2, 0x86, 0xbf, 0x13, 0x45, 0xc5, 0x12, 0x75, 0xdf, 0x5f, 0xd2, 0xa6, 0x2a, 0x4d, 0x1b,
	0xf7, 0xbf, 0x5a, 0xf0, 0xe0, 0x08, 0x11, 0x2f, 0x8b, 0x9c, 0x23, 0xa1, 0x30, 0x51, 0x90, 0x6f,
	0x62, 0x85, 0xc9, 0x09, 0x3b, 0xd9, 0xd3, 0x33, 0x35, 0xf4, 0x2c, 0x2d, 0x3d, 0x5b, 0x43, 0xcf,
	0xd1, 0xd3, 0x73, 0x47, 0xe9, 0x4d, 0xfe, 0x91, 0xde, 0xf4, 0xff, 0xe8, 0xcd, 0xc6, 0xe9, 0xc9,
	0xae, 0x77, 0xf8, 0xa5, 0x29, 0xaa, 0x98, 0x53, 0xf0, 0x2c, 0xd9, 0x75, 0xa7, 0xe5, 0x3d, 0x23,
	0x35, 0x84, 0xf1, 0x0b, 0x41, 0xef, 0x7a, 0xc6, 0xc2, 0x0a, 0x07, 0x43, 0x46, 0xeb, 0x32, 0x3e,
	0x44, 0xef, 0xb5, 0xd1, 0xde, 0xf0, 0xbf, 0x9b, 0x40, 0xde, 0x2b, 0xa5, 0xfe, 0xa7, 0x1b, 0xdb,
	0xdb, 0x27, 0xf9, 0xfb, 0x93, 0x8c, 0x62, 0xf7, 0xaf, 0xe0, 0xe1, 0x1b, 0x14, 0x27, 0x77, 0x82,
	0x16, 0xee, 0xb3, 0x1f, 0x06, 0xdc, 0xff, 0x2d, 0x85, 0xbc, 0x85, 0xb3, 0xfc, 0x68, 0xb5, 0x90,
	0x27, 0xc1, 0xe8, 0xce, 0xb9, 0x38, 0x0f, 0x4e, 0x7e, 0x67, 0xfe, 0x1d, 0xf2, 0x0a, 0xe6, 0xf5,
	0xf0, 0xd8, 0x7d, 0xc1, 0x79, 0xf0, 0xe7, 0x08, 0x8c, 0x54, 0x79, 0x0d, 0x67, 0xc9, 0x51, 0x6b,
	0x84, 0x06, 0x9a, 0x6e, 0xf5, 0x75, 0xae, 0x5d, 0xb0, 0x93, 0xaa, 0x8c, 0x36, 0xae, 0x5a, 0xa6,
	0x57, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x21, 0x6e, 0x20, 0x80, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MediaMetadataClient is the client API for MediaMetadata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MediaMetadataClient interface {
	NewMediaMetadata(ctx context.Context, in *CreateNewMediaMetadataRequest, opts ...grpc.CallOption) (*MediaMetadataResponse, error)
	UpdateMediaMetadata(ctx context.Context, in *UpdateMediaRequest, opts ...grpc.CallOption) (*MediaMetadataResponse, error)
	GetMediaMetadata(ctx context.Context, in *GetMediaMetadataRequest, opts ...grpc.CallOption) (*MediaMetadataResponse, error)
}

type mediaMetadataClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaMetadataClient(cc grpc.ClientConnInterface) MediaMetadataClient {
	return &mediaMetadataClient{cc}
}

func (c *mediaMetadataClient) NewMediaMetadata(ctx context.Context, in *CreateNewMediaMetadataRequest, opts ...grpc.CallOption) (*MediaMetadataResponse, error) {
	out := new(MediaMetadataResponse)
	err := c.cc.Invoke(ctx, "/MediaMetadata/newMediaMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaMetadataClient) UpdateMediaMetadata(ctx context.Context, in *UpdateMediaRequest, opts ...grpc.CallOption) (*MediaMetadataResponse, error) {
	out := new(MediaMetadataResponse)
	err := c.cc.Invoke(ctx, "/MediaMetadata/updateMediaMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaMetadataClient) GetMediaMetadata(ctx context.Context, in *GetMediaMetadataRequest, opts ...grpc.CallOption) (*MediaMetadataResponse, error) {
	out := new(MediaMetadataResponse)
	err := c.cc.Invoke(ctx, "/MediaMetadata/getMediaMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaMetadataServer is the server API for MediaMetadata service.
type MediaMetadataServer interface {
	NewMediaMetadata(context.Context, *CreateNewMediaMetadataRequest) (*MediaMetadataResponse, error)
	UpdateMediaMetadata(context.Context, *UpdateMediaRequest) (*MediaMetadataResponse, error)
	GetMediaMetadata(context.Context, *GetMediaMetadataRequest) (*MediaMetadataResponse, error)
}

// UnimplementedMediaMetadataServer can be embedded to have forward compatible implementations.
type UnimplementedMediaMetadataServer struct {
}

func (*UnimplementedMediaMetadataServer) NewMediaMetadata(ctx context.Context, req *CreateNewMediaMetadataRequest) (*MediaMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewMediaMetadata not implemented")
}
func (*UnimplementedMediaMetadataServer) UpdateMediaMetadata(ctx context.Context, req *UpdateMediaRequest) (*MediaMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMediaMetadata not implemented")
}
func (*UnimplementedMediaMetadataServer) GetMediaMetadata(ctx context.Context, req *GetMediaMetadataRequest) (*MediaMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMediaMetadata not implemented")
}

func RegisterMediaMetadataServer(s *grpc.Server, srv MediaMetadataServer) {
	s.RegisterService(&_MediaMetadata_serviceDesc, srv)
}

func _MediaMetadata_NewMediaMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewMediaMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaMetadataServer).NewMediaMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MediaMetadata/NewMediaMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaMetadataServer).NewMediaMetadata(ctx, req.(*CreateNewMediaMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaMetadata_UpdateMediaMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaMetadataServer).UpdateMediaMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MediaMetadata/UpdateMediaMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaMetadataServer).UpdateMediaMetadata(ctx, req.(*UpdateMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaMetadata_GetMediaMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaMetadataServer).GetMediaMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MediaMetadata/GetMediaMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaMetadataServer).GetMediaMetadata(ctx, req.(*GetMediaMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MediaMetadata_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MediaMetadata",
	HandlerType: (*MediaMetadataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "newMediaMetadata",
			Handler:    _MediaMetadata_NewMediaMetadata_Handler,
		},
		{
			MethodName: "updateMediaMetadata",
			Handler:    _MediaMetadata_UpdateMediaMetadata_Handler,
		},
		{
			MethodName: "getMediaMetadata",
			Handler:    _MediaMetadata_GetMediaMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/media_metadata/mediametadata_service.proto",
}
