// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/timeshift_service_server/timeshift_service.proto

package timeshift_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TimeShiftRequest struct {
	MediaId              int32    `protobuf:"varint,1,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeShiftRequest) Reset()         { *m = TimeShiftRequest{} }
func (m *TimeShiftRequest) String() string { return proto.CompactTextString(m) }
func (*TimeShiftRequest) ProtoMessage()    {}
func (*TimeShiftRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329f5050c796673e, []int{0}
}

func (m *TimeShiftRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeShiftRequest.Unmarshal(m, b)
}
func (m *TimeShiftRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeShiftRequest.Marshal(b, m, deterministic)
}
func (m *TimeShiftRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeShiftRequest.Merge(m, src)
}
func (m *TimeShiftRequest) XXX_Size() int {
	return xxx_messageInfo_TimeShiftRequest.Size(m)
}
func (m *TimeShiftRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeShiftRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TimeShiftRequest proto.InternalMessageInfo

func (m *TimeShiftRequest) GetMediaId() int32 {
	if m != nil {
		return m.MediaId
	}
	return 0
}

type TimeShiftSequenceRequest struct {
	SequenceId           int32    `protobuf:"varint,1,opt,name=sequenceId,proto3" json:"sequenceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeShiftSequenceRequest) Reset()         { *m = TimeShiftSequenceRequest{} }
func (m *TimeShiftSequenceRequest) String() string { return proto.CompactTextString(m) }
func (*TimeShiftSequenceRequest) ProtoMessage()    {}
func (*TimeShiftSequenceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329f5050c796673e, []int{1}
}

func (m *TimeShiftSequenceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeShiftSequenceRequest.Unmarshal(m, b)
}
func (m *TimeShiftSequenceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeShiftSequenceRequest.Marshal(b, m, deterministic)
}
func (m *TimeShiftSequenceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeShiftSequenceRequest.Merge(m, src)
}
func (m *TimeShiftSequenceRequest) XXX_Size() int {
	return xxx_messageInfo_TimeShiftSequenceRequest.Size(m)
}
func (m *TimeShiftSequenceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeShiftSequenceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TimeShiftSequenceRequest proto.InternalMessageInfo

func (m *TimeShiftSequenceRequest) GetSequenceId() int32 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

type TimeShitResponse struct {
	MediaId                  int32                      `protobuf:"varint,1,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	Name                     string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SiteName                 string                     `protobuf:"bytes,3,opt,name=siteName,proto3" json:"siteName,omitempty"`
	Length                   int64                      `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Status                   int32                      `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Thumbnail                string                     `protobuf:"bytes,6,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	ProjectId                int32                      `protobuf:"varint,7,opt,name=projectId,proto3" json:"projectId,omitempty"`
	AwsBucketWholeMedia      string                     `protobuf:"bytes,8,opt,name=awsBucketWholeMedia,proto3" json:"awsBucketWholeMedia,omitempty"`
	AwsStorageNameWholeMedia string                     `protobuf:"bytes,9,opt,name=awsStorageNameWholeMedia,proto3" json:"awsStorageNameWholeMedia,omitempty"`
	Keywords                 []string                   `protobuf:"bytes,10,rep,name=keywords,proto3" json:"keywords,omitempty"`
	CreatedAt                int64                      `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt                int64                      `protobuf:"varint,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	MediaUrl                 string                     `protobuf:"bytes,13,opt,name=mediaUrl,proto3" json:"mediaUrl,omitempty"`
	Data                     []*ChunkResolutionResponse `protobuf:"bytes,14,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                   `json:"-"`
	XXX_unrecognized         []byte                     `json:"-"`
	XXX_sizecache            int32                      `json:"-"`
}

func (m *TimeShitResponse) Reset()         { *m = TimeShitResponse{} }
func (m *TimeShitResponse) String() string { return proto.CompactTextString(m) }
func (*TimeShitResponse) ProtoMessage()    {}
func (*TimeShitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_329f5050c796673e, []int{2}
}

func (m *TimeShitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeShitResponse.Unmarshal(m, b)
}
func (m *TimeShitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeShitResponse.Marshal(b, m, deterministic)
}
func (m *TimeShitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeShitResponse.Merge(m, src)
}
func (m *TimeShitResponse) XXX_Size() int {
	return xxx_messageInfo_TimeShitResponse.Size(m)
}
func (m *TimeShitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeShitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TimeShitResponse proto.InternalMessageInfo

func (m *TimeShitResponse) GetMediaId() int32 {
	if m != nil {
		return m.MediaId
	}
	return 0
}

func (m *TimeShitResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TimeShitResponse) GetSiteName() string {
	if m != nil {
		return m.SiteName
	}
	return ""
}

func (m *TimeShitResponse) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *TimeShitResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TimeShitResponse) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *TimeShitResponse) GetProjectId() int32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *TimeShitResponse) GetAwsBucketWholeMedia() string {
	if m != nil {
		return m.AwsBucketWholeMedia
	}
	return ""
}

func (m *TimeShitResponse) GetAwsStorageNameWholeMedia() string {
	if m != nil {
		return m.AwsStorageNameWholeMedia
	}
	return ""
}

func (m *TimeShitResponse) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *TimeShitResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *TimeShitResponse) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *TimeShitResponse) GetMediaUrl() string {
	if m != nil {
		return m.MediaUrl
	}
	return ""
}

func (m *TimeShitResponse) GetData() []*ChunkResolutionResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type TimeShiftSequenceResponse struct {
	SequenceId           int32                      `protobuf:"varint,1,opt,name=sequenceId,proto3" json:"sequenceId,omitempty"`
	Name                 string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProjectId            int32                      `protobuf:"varint,3,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Status               int32                      `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            int64                      `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64                      `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Data                 []*ChunkResolutionResponse `protobuf:"bytes,14,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TimeShiftSequenceResponse) Reset()         { *m = TimeShiftSequenceResponse{} }
func (m *TimeShiftSequenceResponse) String() string { return proto.CompactTextString(m) }
func (*TimeShiftSequenceResponse) ProtoMessage()    {}
func (*TimeShiftSequenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_329f5050c796673e, []int{3}
}

func (m *TimeShiftSequenceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeShiftSequenceResponse.Unmarshal(m, b)
}
func (m *TimeShiftSequenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeShiftSequenceResponse.Marshal(b, m, deterministic)
}
func (m *TimeShiftSequenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeShiftSequenceResponse.Merge(m, src)
}
func (m *TimeShiftSequenceResponse) XXX_Size() int {
	return xxx_messageInfo_TimeShiftSequenceResponse.Size(m)
}
func (m *TimeShiftSequenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeShiftSequenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TimeShiftSequenceResponse proto.InternalMessageInfo

func (m *TimeShiftSequenceResponse) GetSequenceId() int32 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

func (m *TimeShiftSequenceResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TimeShiftSequenceResponse) GetProjectId() int32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *TimeShiftSequenceResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TimeShiftSequenceResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *TimeShiftSequenceResponse) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *TimeShiftSequenceResponse) GetData() []*ChunkResolutionResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type ChunkResolutionResponse struct {
	Resolution           string           `protobuf:"bytes,1,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Chunks               []*ChunkResponse `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ChunkResolutionResponse) Reset()         { *m = ChunkResolutionResponse{} }
func (m *ChunkResolutionResponse) String() string { return proto.CompactTextString(m) }
func (*ChunkResolutionResponse) ProtoMessage()    {}
func (*ChunkResolutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_329f5050c796673e, []int{4}
}

func (m *ChunkResolutionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkResolutionResponse.Unmarshal(m, b)
}
func (m *ChunkResolutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkResolutionResponse.Marshal(b, m, deterministic)
}
func (m *ChunkResolutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkResolutionResponse.Merge(m, src)
}
func (m *ChunkResolutionResponse) XXX_Size() int {
	return xxx_messageInfo_ChunkResolutionResponse.Size(m)
}
func (m *ChunkResolutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkResolutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkResolutionResponse proto.InternalMessageInfo

func (m *ChunkResolutionResponse) GetResolution() string {
	if m != nil {
		return m.Resolution
	}
	return ""
}

func (m *ChunkResolutionResponse) GetChunks() []*ChunkResponse {
	if m != nil {
		return m.Chunks
	}
	return nil
}

type ChunkResponse struct {
	ChunkId              int32    `protobuf:"varint,1,opt,name=chunkId,proto3" json:"chunkId,omitempty"`
	Position             int32    `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	AwsBucketName        string   `protobuf:"bytes,3,opt,name=awsBucketName,proto3" json:"awsBucketName,omitempty"`
	AwsStorageName       string   `protobuf:"bytes,4,opt,name=awsStorageName,proto3" json:"awsStorageName,omitempty"`
	Length               float64  `protobuf:"fixed64,5,opt,name=length,proto3" json:"length,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ChunksUrl            string   `protobuf:"bytes,7,opt,name=chunksUrl,proto3" json:"chunksUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChunkResponse) Reset()         { *m = ChunkResponse{} }
func (m *ChunkResponse) String() string { return proto.CompactTextString(m) }
func (*ChunkResponse) ProtoMessage()    {}
func (*ChunkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_329f5050c796673e, []int{5}
}

func (m *ChunkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkResponse.Unmarshal(m, b)
}
func (m *ChunkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkResponse.Marshal(b, m, deterministic)
}
func (m *ChunkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkResponse.Merge(m, src)
}
func (m *ChunkResponse) XXX_Size() int {
	return xxx_messageInfo_ChunkResponse.Size(m)
}
func (m *ChunkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkResponse proto.InternalMessageInfo

func (m *ChunkResponse) GetChunkId() int32 {
	if m != nil {
		return m.ChunkId
	}
	return 0
}

func (m *ChunkResponse) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *ChunkResponse) GetAwsBucketName() string {
	if m != nil {
		return m.AwsBucketName
	}
	return ""
}

func (m *ChunkResponse) GetAwsStorageName() string {
	if m != nil {
		return m.AwsStorageName
	}
	return ""
}

func (m *ChunkResponse) GetLength() float64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ChunkResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ChunkResponse) GetChunksUrl() string {
	if m != nil {
		return m.ChunksUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*TimeShiftRequest)(nil), "TimeShiftRequest")
	proto.RegisterType((*TimeShiftSequenceRequest)(nil), "TimeShiftSequenceRequest")
	proto.RegisterType((*TimeShitResponse)(nil), "TimeShitResponse")
	proto.RegisterType((*TimeShiftSequenceResponse)(nil), "TimeShiftSequenceResponse")
	proto.RegisterType((*ChunkResolutionResponse)(nil), "ChunkResolutionResponse")
	proto.RegisterType((*ChunkResponse)(nil), "ChunkResponse")
}

func init() {
	proto.RegisterFile("proto/timeshift_service_server/timeshift_service.proto", fileDescriptor_329f5050c796673e)
}

var fileDescriptor_329f5050c796673e = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xe3, 0xc4, 0x89, 0xa7, 0x24, 0x82, 0x45, 0x82, 0x6d, 0x40, 0x28, 0xb2, 0x50, 0x95,
	0x43, 0x15, 0x50, 0x91, 0x38, 0xf4, 0x46, 0x38, 0x54, 0x39, 0x80, 0x90, 0x53, 0xe0, 0x88, 0xb6,
	0xf6, 0x34, 0x31, 0x89, 0x7f, 0xf0, 0xae, 0x89, 0x78, 0x22, 0x5e, 0x89, 0x37, 0xe0, 0xc8, 0x2b,
	0xa0, 0x9d, 0xd8, 0xeb, 0x24, 0x4d, 0x40, 0x3d, 0xd9, 0xf3, 0x7d, 0x3b, 0x3b, 0x3b, 0xdf, 0xfc,
	0xc0, 0xeb, 0x2c, 0x4f, 0x55, 0xfa, 0x42, 0x45, 0x31, 0xca, 0x79, 0x74, 0xa3, 0xbe, 0x48, 0xcc,
	0xbf, 0x47, 0x01, 0xd2, 0x17, 0xf3, 0xdb, 0xc4, 0x88, 0x1c, 0xbc, 0x33, 0xb8, 0x7f, 0x15, 0xc5,
	0x38, 0xd5, 0x94, 0x8f, 0xdf, 0x0a, 0x94, 0x8a, 0x71, 0x68, 0xc7, 0x18, 0x46, 0x62, 0x12, 0x72,
	0x6b, 0x60, 0x0d, 0x5b, 0x7e, 0x65, 0x7a, 0x17, 0xc0, 0xcd, 0xe9, 0xa9, 0x3e, 0x9d, 0x04, 0x58,
	0x79, 0x3d, 0x03, 0x90, 0x25, 0x64, 0x1c, 0x37, 0x10, 0xef, 0x97, 0x6d, 0x42, 0x29, 0x1f, 0x65,
	0x96, 0x26, 0x12, 0x0f, 0x87, 0x62, 0x0c, 0x9a, 0x89, 0x88, 0x91, 0x37, 0x06, 0xd6, 0xd0, 0xf5,
	0xe9, 0x9f, 0xf5, 0xa1, 0x23, 0x23, 0x85, 0xef, 0x35, 0x6e, 0x13, 0x6e, 0x6c, 0xf6, 0x08, 0x9c,
	0x25, 0x26, 0x33, 0x35, 0xe7, 0xcd, 0x81, 0x35, 0xb4, 0xfd, 0xd2, 0xd2, 0xb8, 0x54, 0x42, 0x15,
	0x92, 0xb7, 0x28, 0x40, 0x69, 0xb1, 0xa7, 0xe0, 0xaa, 0x79, 0x11, 0x5f, 0x27, 0x22, 0x5a, 0x72,
	0x87, 0x2e, 0xab, 0x01, 0xcd, 0x66, 0x79, 0xfa, 0x15, 0x03, 0x35, 0x09, 0x79, 0x9b, 0x1c, 0x6b,
	0x80, 0xbd, 0x84, 0x87, 0x62, 0x25, 0xc7, 0x45, 0xb0, 0x40, 0xf5, 0x79, 0x9e, 0x2e, 0xf1, 0x9d,
	0x7e, 0x34, 0xef, 0xd0, 0x2d, 0xfb, 0x28, 0x76, 0x01, 0x5c, 0xac, 0xe4, 0x54, 0xa5, 0xb9, 0x98,
	0xd1, 0x7b, 0x37, 0xdc, 0x5c, 0x72, 0x3b, 0xc8, 0xeb, 0xac, 0x17, 0xf8, 0x63, 0x95, 0xe6, 0xa1,
	0xe4, 0x30, 0xb0, 0x75, 0xd6, 0x95, 0xad, 0xdf, 0x19, 0xe4, 0x28, 0x14, 0x86, 0x6f, 0x14, 0x3f,
	0xa6, 0xc4, 0x6b, 0x40, 0xb3, 0x45, 0x16, 0x96, 0xec, 0xbd, 0x35, 0x6b, 0x00, 0x7d, 0x2f, 0x89,
	0xfd, 0x31, 0x5f, 0xf2, 0xee, 0x5a, 0xcd, 0xca, 0x66, 0x67, 0xd0, 0x0c, 0x85, 0x12, 0xbc, 0x37,
	0xb0, 0x87, 0xc7, 0xe7, 0x7c, 0xf4, 0x76, 0x5e, 0x24, 0x0b, 0x1f, 0x65, 0xba, 0x2c, 0x54, 0x94,
	0x26, 0x55, 0xfd, 0x7c, 0x3a, 0xe5, 0xfd, 0xb1, 0xe0, 0x64, 0x4f, 0x5f, 0x94, 0x35, 0xfe, 0x4f,
	0x63, 0xec, 0xad, 0xf4, 0x96, 0xfe, 0xf6, 0xae, 0xfe, 0x75, 0x4d, 0x9b, 0xbb, 0x35, 0xad, 0xd5,
	0x68, 0xfd, 0x53, 0x0d, 0x67, 0x57, 0x8d, 0xbb, 0x65, 0x2c, 0xe0, 0xf1, 0x81, 0x03, 0x3a, 0xdd,
	0xdc, 0xa0, 0x94, 0xae, 0xeb, 0x6f, 0x20, 0xec, 0x14, 0x9c, 0x40, 0xbb, 0x4a, 0xde, 0xa0, 0x50,
	0x3d, 0x13, 0x6a, 0x1d, 0xa0, 0x64, 0xbd, 0xdf, 0x16, 0x74, 0xb7, 0x18, 0x3d, 0x2c, 0xc4, 0xd5,
	0xc3, 0x52, 0x9a, 0xba, 0x94, 0x59, 0x2a, 0x23, 0x8a, 0xd8, 0x20, 0xca, 0xd8, 0xec, 0x39, 0x74,
	0x4d, 0x47, 0x6e, 0x4c, 0xce, 0x36, 0xc8, 0x4e, 0xa1, 0xb7, 0xdd, 0x80, 0x24, 0xad, 0xeb, 0xef,
	0xa0, 0x1b, 0x63, 0xa6, 0xf5, 0xb5, 0xcc, 0x98, 0x6d, 0x49, 0xef, 0xec, 0x91, 0x7e, 0x9d, 0x95,
	0xee, 0xb5, 0xf6, 0x7a, 0xd8, 0x0c, 0x70, 0xfe, 0xd3, 0x02, 0xf7, 0xaa, 0xda, 0x4f, 0x6c, 0x0c,
	0xfc, 0x12, 0x15, 0xb5, 0x3e, 0xa5, 0x3f, 0x49, 0x6e, 0xd2, 0x3c, 0x16, 0x94, 0xcb, 0x83, 0xd1,
	0xee, 0xb2, 0xea, 0x1b, 0xc8, 0x2c, 0x15, 0xef, 0x88, 0x7d, 0x82, 0x27, 0x97, 0x68, 0x3a, 0xf1,
	0xd6, 0x35, 0x27, 0xa3, 0x43, 0x5b, 0xac, 0xdf, 0x1f, 0x1d, 0x6c, 0x64, 0xef, 0x68, 0xdc, 0x81,
	0xe6, 0x2c, 0xcf, 0x82, 0x0f, 0xd6, 0xb5, 0x43, 0xeb, 0xf3, 0xd5, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x42, 0x1e, 0x60, 0x31, 0x78, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TimeshiftClient is the client API for Timeshift service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TimeshiftClient interface {
	GetMediaChunkInformation(ctx context.Context, in *TimeShiftRequest, opts ...grpc.CallOption) (*TimeShitResponse, error)
	GetSequenceChunkInformation(ctx context.Context, in *TimeShiftSequenceRequest, opts ...grpc.CallOption) (*TimeShiftSequenceResponse, error)
}

type timeshiftClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeshiftClient(cc grpc.ClientConnInterface) TimeshiftClient {
	return &timeshiftClient{cc}
}

func (c *timeshiftClient) GetMediaChunkInformation(ctx context.Context, in *TimeShiftRequest, opts ...grpc.CallOption) (*TimeShitResponse, error) {
	out := new(TimeShitResponse)
	err := c.cc.Invoke(ctx, "/Timeshift/GetMediaChunkInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeshiftClient) GetSequenceChunkInformation(ctx context.Context, in *TimeShiftSequenceRequest, opts ...grpc.CallOption) (*TimeShiftSequenceResponse, error) {
	out := new(TimeShiftSequenceResponse)
	err := c.cc.Invoke(ctx, "/Timeshift/GetSequenceChunkInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeshiftServer is the server API for Timeshift service.
type TimeshiftServer interface {
	GetMediaChunkInformation(context.Context, *TimeShiftRequest) (*TimeShitResponse, error)
	GetSequenceChunkInformation(context.Context, *TimeShiftSequenceRequest) (*TimeShiftSequenceResponse, error)
}

// UnimplementedTimeshiftServer can be embedded to have forward compatible implementations.
type UnimplementedTimeshiftServer struct {
}

func (*UnimplementedTimeshiftServer) GetMediaChunkInformation(ctx context.Context, req *TimeShiftRequest) (*TimeShitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMediaChunkInformation not implemented")
}
func (*UnimplementedTimeshiftServer) GetSequenceChunkInformation(ctx context.Context, req *TimeShiftSequenceRequest) (*TimeShiftSequenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSequenceChunkInformation not implemented")
}

func RegisterTimeshiftServer(s *grpc.Server, srv TimeshiftServer) {
	s.RegisterService(&_Timeshift_serviceDesc, srv)
}

func _Timeshift_GetMediaChunkInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeShiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeshiftServer).GetMediaChunkInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Timeshift/GetMediaChunkInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeshiftServer).GetMediaChunkInformation(ctx, req.(*TimeShiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Timeshift_GetSequenceChunkInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeShiftSequenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeshiftServer).GetSequenceChunkInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Timeshift/GetSequenceChunkInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeshiftServer).GetSequenceChunkInformation(ctx, req.(*TimeShiftSequenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Timeshift_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Timeshift",
	HandlerType: (*TimeshiftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMediaChunkInformation",
			Handler:    _Timeshift_GetMediaChunkInformation_Handler,
		},
		{
			MethodName: "GetSequenceChunkInformation",
			Handler:    _Timeshift_GetSequenceChunkInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/timeshift_service_server/timeshift_service.proto",
}
